version: "3.7"

services:
  mysql-practice:
    image: mysql
    environment:
      MYSQL_DATABASE: community
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  kyoongdev-spring:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db-mysql
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge